### ISSUE TITLE
New-HPOVStorageVolume fails without -StorageSystem

### ISSUE THREAD

**Issue by VincentBerger** [HewlettPackard/POSH-HPOneView#102]
OneView PowerShell version 2.0.340

The help for New-HPOVStorage Volume says:
    -StorageSystem [<StorageSystem>]
        When the Storage Pool name is not unique, specify the Storage System name the pool is managed/associate with.

Yet when I do New-HPOVStorageVolume "Cluster VMFS 1" -PoolName "FST_CPG1" -size 400 -shared -ApplianceConnection $myConnection
It fails with:
New-HPOVStorageVolume : Cannot validate argument on parameter 'StorageSystem'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

The appliance has only one storage system and one pool named FST_CPG1
I believe the problem is on line 24680 of the module when you call Get-HPOVStoragePool with -storageSystem $StorageSystem which is null

Verbose output attached
[New-HPOVStorageVolume-Verbose.txt](https://github.com/HewlettPackard/POSH-HPOneView/files/230035/New-HPOVStorageVolume-Verbose.txt)

Thanks !

**Comment by ChrisLynchHPE** [comment]
Yes, this is a bug.  No, it is not that line per-say.  I identified the problem. The logic handling the `StoragePool` parameter had duplicate logic that shouldn't have been present.

Also, as a workaround, use a `StoragePool` object instead of using the name.  That will bypass the code that needs to be fixed.  The `-StoragePool` parameter can be a pipeline object, which then you do not need the `-ApplianceConnection` parameter in your `New-HPOVStorageVolume` call.

**Comment by ChrisLynchHPE** [comment]
This is fixed in [Release 2.0.368.0](https://github.com/HewlettPackard/POSH-HPOneView/releases/tag/v2.0.368.0).

Closing.
