### ISSUE TITLE
New-HPOVBackup causes authorization error in PowerShell transcript

### ISSUE THREAD

**Issue by MWalterDE** [HewlettPackard/POSH-HPOneView#264]
### Expected Behavior
HPE OneView configuration backup to remote Windows Server 2012 R2 system with OneView internal user account with "Backup Administrator" permissions.

### Actual Behavior
Backup is being successfully written, but the following error message is logged in the PowerShell transcript:
PS>TerminatingError(Send-HPOVRequest): "[Send-HPOVRequest]: Authorization error: User not authorized for this operation..  Request was 'GET' at '/rest/roles'. "

### Steps to reproduce
"New-HPOVBackup -Location E:\" with PowerShell transcript turned on.

### Version Information
HPE OneView PowerShell Library Version (`Get-HPOVVersion`): 3.0.1264.2772
HPE OneView Appliance Version:  3.00.05-0271823
Output from `$PSVersionTable` on your Windows Host:
Name                           Value
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by ChrisLynchHPE** [comment]
What "transcript" are you referring to?  Are you trying to "peek" into `$error` to see if there are errors in the history?  If so, that is bad practice.  You should be using `-ErrorAction Stop|SilentlyContinue` (where supported by the Get-HPOV Cmdlet) and `Try{} Catch{}` blocks to capture terminating errors.

**Comment by MWalterDE** [comment]
We are using a slightly modified "Appliance_Backup_Sample.ps1" script, but only stored credentials and a cleanup task have been added.
The trace file is being activated with the following command:
---
#Begin Command Trace for logging purposes
Start-Transcript $Location\Appliance_backup$(get-date -uformat %y%m%d).trace
---

You can see the error logged in there:
---
**********************
Windows PowerShell transcript start
Start time: 20170412085443
Username: XXX
RunAs User: YYY
Machine: ZZZ (Microsoft Windows NT 6.3.9600.0)
Host Application: C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy bypass -file E:\HPEOneView_Backup\Appliance_Backup.PS1
Process ID: 4752
**********************
Transcript started, output file is E:\HPEOneView_Backup\Appliance_backup170412.trace

PS>TerminatingError(Send-HPOVRequest): "[Send-HPOVRequest]: Authorization error: User not authorized for this operation..  Request was 'GET' at '/rest/roles'. "
---

**Comment by ChrisLynchHPE** [comment]
Yes, and that is expected.  When the user logs into the appliance, we collect what roles the user account is a member of.  The Backup Administrator does not have access to that URI, and the terminating error is captured within a `Try{} Catch{}` block, and is expected behavior.  I would suggest you look at a different method to generate a log of your backups, say with [New-Event](https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Utility/New-Event), or [Write-Log](https://gallery.technet.microsoft.com/scriptcenter/Write-Log-PowerShell-999c32d0) on TechNet (there are plenty of other good examples you can [find](https://www.bing.com/search?q=powershell+log+file&form=EDGEAR&qs=PF&cvid=d48e58324ccd4018a2e239d33cfb029e&pq=powershell+log+file&cc=US&setlang=en-US&elv=AXXfrEiqqD9r3GuelwApulolhOVEBiimuRR5A0kKKlbnkOD4vKW0NCWA2zf4kUOixWZBUW6lfnlcXIA02fDKOI%21K07FtpAsSQqpOj0x*tM1l)).

**Comment by ChrisLynchHPE** [comment]
Closing issue.  If you feel there is something further to discuss on this topic, we can re-open it.
