### ISSUE TITLE
Version check

### ISSUE THREAD

**Issue by CermakPOI** [HewlettPackard/POSH-HPOneView#48]
The command 
Get-HPOVVersion -CheckOnline
asks for a connection to the One View Appliance - Why? It should check if there is a new Powershell module available, why does it need the Connection to  HPOV Appliance?

When connected i see that the variable is not initialized properly: $_Connections
Get-HPOVVersion -CheckOnline
You cannot call a method on a null-valued expression.
At C:\windows\system32\windowspowershell\v1.0\Modules\HPOneView.200\HPOneView.200.psm1:8077 char:6
+                     [void]$_Connections.Add($_connection.Name)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by CermakPOI** [comment]
The correction would be to add this line at lineno 8066
$_Connections = New-Object System.Collections.ArrayList

**Comment by ChrisLynchHP** [comment]
The original intention was that users would want to know the ApplianceVersion and the library version installed.  The CheckOnline was to help look for updates.  The assumption was that users would have one connection already established, which is why `-ApplianceConnection` is not a mandatory parameter, and its default value is `${Global:ConnectedSessions}`.  We can add some additional logic to perform the online check only if that is the only parameter and no appliance connections exist.  That will mean a new command syntax will be made, separating `-CheckOnline` from the other parameters.

Removing `[ValidateNotNullorEmpty()]` from the `-ApplianceConnection` parameter isn't going to resolve this.  That advanced parameter option is to validate that the user doesn't provide a `$null` or empty value for `-ApplianceConnection` when they explicitly provide the parameter name in the call to the CMDLET.

**Comment by CermakPOI** [comment]
My correction resolves the immediate error:
```powershell
$_Connections = New-Object System.Collections.ArrayList
```
The real main issue here is that the function asks for the -ApplianceConnection even tough the global variable already exists..
There are other functions that have the same issue.
In my opinion: either use/support the global variable everywhere or require a specific parameter always - the first suggestion would be easier for everybody ;-)

The -checkonline does not find the url, bute maybe that's because of our proxy...

**Comment by ChrisLynchHP** [comment]
The problem was that the Begin code block was implemented incorrectly in Get-HPOVVersion.  It is now fixed.

> In my opinion: either use/support the global variable everywhere or require a specific parameter always - the first suggestion would be easier for everybody ;-)

We do.  The -ApplianceConnect parameter is optional for CMDLETs that can be optional (when we can and operations can be performed across all connected appliances, mainly `Get-HPOV` cmdlets), and others require it (where unique resources per appliance cannot be used across appliance connections, mostly `New-HPOV` and `Set-HPOV` cmdlets.).  All is documented in the `Get-Help {cmdlet}`.  We can't just globally require the parameter for every single cmdlet.

**Comment by ChrisLynchHP** [comment]
Can you test the following code to make sure Proxy Support I'm adding works:

```PowerShell
[String]$script:repository  = "https://api.github.com/repos/HewlettPackard/POSH-HPOneView/releases"
[Uri]$_ProxyUri = $null

$_Options = @{Uri = $script:repository}

$_Proxy = [System.Net.WebRequest]::GetSystemWebProxy()

$_Proxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
$_ProxyUri = $_Proxy.GetProxy($_Options.Uri)

if ($_ProxyUri.OriginalString -ne $_Options.Uri)
{

	$_Options.Add('Proxy',$_proxyUri)
	$_Options.Add('ProxyUseDefaultCredentials', $true)
	
}

$resp = Invoke-RestMethod @_Options

$resp.name
```

You should see a list of published release Names like:

```
Release 2.0.40.0
Release 1.20.275.0
Release 2.0.10.15
Release 1.20.255.0
Release 1.20.251.0
Release 1.20.240.0
Release 1.20.233.0
Scripted node migration from HP SIM to HP OneView
Release 1.20.208.0
Release 1.20.166.0
Release 1.20.0164.0
Re-Release 1.20.0124.2
Release 1.20.0112.0
Release 1.20.0109.0
Release 1.20.0078.0
Release 1.20.0077.0
Release 1.10.1506
Release 1.20.0050.0
Release 1.10.1476
Release 1.20.0.0007
Release 1.10.1447.1
Release 1.10.1432
Release 1.10.1415.1
HP Virtual Connect to OneView Migration Tool
Release 1.10.1378
```

**Comment by CermakPOI** [comment]
Your code is working from my Client

```powershell
...
PS U:\> $resp.name
Release 2.0.67.0
Release 2.0.40.0
Release 1.20.275.0
Release 2.0.10.15
Release 1.20.255.0
Release 1.20.251.0
Release 1.20.240.0
Release 1.20.233.0
Scripted node migration from HP SIM to HP OneView
Release 1.20.208.0
Release 1.20.166.0
Release 1.20.0164.0
Re-Release 1.20.0124.2
Release 1.20.0112.0
Release 1.20.0109.0
Release 1.20.0078.0
Release 1.20.0077.0
Release 1.10.1506
Release 1.20.0050.0
Release 1.10.1476
Release 1.20.0.0007
Release 1.10.1447.1
Release 1.10.1432
Release 1.10.1415.1
HP Virtual Connect to OneView Migration Tool
Release 1.10.1378
```

Is there a way to use a internal repository?
