### ISSUE TITLE
Get-OVIloSso to auth to HPEiLOCmdlets

### ISSUE THREAD

**Issue by ericholton** [HewlettPackard/POSH-HPOneView#589]
Hi, Is it possible to use Get-OVServer -Name "ServerName" | Get-OVIloSso and use the connection with the HPEiLOCmdlets? 

I would like to be able to reconfigure iLO without having to modify the server profile and without having to first create credentials on the iLO. 

It seems to only work with HPERESTCmdlets but I hate to reinvent the wheel when there are HPEiLOCmdlets functions that do what I need.

Thanks,
Eric

**Comment by ChrisLynchHPE** [comment]
Unfortunately, the HPEiLOCmdlets do not use Redfish specs, so they cannot support session token authentication.  You will need to transition using the HPERESTCmdlets.

**Comment by jullienl** [comment]
In fact since some recent versions of HPEiLOCmdlets, `Connect-HPEiLO` can be used with the `XAuthToken` parameter where you can specify the iLO SSO session key but this parameter is only supported on iLO5.

An example on how to use it with iLO5 servers:  [Set iLO5 to FIPS mode.ps1](https://github.com/jullienl/HPE-Synergy-OneView-demos/blob/master/Powershell/iLO/Set%20iLO5%20to%20FIPS%20mode.ps1) 

An example on how to use it with iLO4 and iLO5 servers, see [Upgrade iLO FW without iLO local user.ps1](https://github.com/jullienl/HPE-Synergy-OneView-demos/blob/master/Powershell/iLO/Upgrade%20iLO%20FW%20without%20iLO%20local%20user.ps1)

**Comment by ericholton** [comment]
@jullienl, Thank you very much! Your guidance was exactly what I needed.
