### ISSUE TITLE
boot vlan

### ISSUE THREAD

**Issue by davidwallis** [HewlettPackard/POSH-HPOneView#591]
I'm struggling to find how to set the bootVlanId

exporting a template and I can see the attribute under connections, boot:

![image](https://user-images.githubusercontent.com/13855486/151372477-619ee4b6-2843-4e5c-9802-81da01400a37.png)

it appears we need to configure this in the bios but struggling find any automation around this which is disappointing. 

any pointers?

**Comment by jullienl** [comment]
The reason you are struggling is because the `bootvlanID` is not available with a PXE boot enabled connection but only for a connection of FunctionType `iSCSI` (as documented in the REST API Reference). Furthermore, the Boot VLAN ID cannot even be defined in the GUI:

![image](https://user-images.githubusercontent.com/13134334/151783270-c106f903-8fcc-4283-851f-5456ee5c4f8d.png)

That's why the parameter in your screenshot is `null`. In recent versions of OneView (I don't know which version you are using), this `bootvlanID `doesn't even exist:

![image](https://user-images.githubusercontent.com/13134334/151781888-53881575-d0ee-4c5e-becb-0a2a645d067c.png)

I assume this is a Synergy environment (your screenshot shows a Synergy mezzanine port ID definition), so why are you trying to use a VLAN ID for PXE boot? Can't you just use the native option for your network set or, if you are not using a network set, just connect that port to a network (in which case the connection is not tagged) and let Virtual Connect tag the PXE traffic (using that network's VLAN ID) when leaving the Virtual Connect uplink set?

**Comment by davidwallis** [comment]
Thanks for taking the time to reply, The reason I was trying to do this is more a legacy one internally in that the native Vlan is typically set to lets say 123 which is an unused vlan for 'security reasons'. The trunk / uplink has that configured, but our VMWare autodeploy server is in a specific vlan - at the moment we have made that the native vlan on the network set and that works, but I was trying to replicate how it was pre-synergy frame that we have just bought without needing to make changes to the rest of our environment and go through an onerous process of getting a simple config change agreed.

The option for the VLAN is available in the bios - I'm just struggling to find it exposed via any rest api or these modules. 
System Utils - Sys Config - Bios / Plat RBSU - Network Options - Network Boot Options - VLAN Control
Vlan Control: Enabled
VLANID: 123

The boot vlan being associated with iSCSI makes perfect sense and I never would have pieced that together as we don't currently use iSCSI :D

**Comment by jullienl** [comment]
This `VLAN control` option in the BIOS is available as long as you do not use Virtual Connect modules that require a server controlled by a OneView Server Profile resource. With VC modules, this option is not supported (unless you use an iSCSI function) and is therefore not exposed via the API for a standard Ethernet connection. 

So you have no choice but to play with the native option in your uplink set, unless you use a script that would change the server profile definition before and after provisioning. Before, with PXE connections 1 and 2 disconnected from the `network set` but connected to the secure VLAN only (in this case, the PXE traffic is not tagged on the network card, regardless of the native or non-native configuration of your uplink set.) and after provisioning, connected to the `network set` once the OS is installed (this change can be made on the fly). I hope this helps.

**Comment by davidwallis** [comment]
would the above option change the mac address assignment of the box? (I don't really want to get into statically assigning these) as these are what we are using in autodeploy for the rules, coupled with config around dhcp.

Thanks for taking the time to explain.

**Comment by jullienl** [comment]
No, changing a network assigned to a Server Profile connection does not change the MAC address assignment. 

You can refer to https://support.hpe.com/hpesc/public/docDisplay?docId=sd00001194en_us&docLocale=en_US&page=s_profiles-about-editing.html to get the list of all changes you can do when the server is powered ON.

**Comment by davidwallis** [comment]
Ok thanks, will have a play and see how we get on.

**Comment by ChrisLynchHPE** [comment]
Closing conversation due to no further activity.  This issue can be re-opened if needed.
