### ISSUE TITLE
Oneview 2.00 POSH Library connection error

### ISSUE THREAD

**Issue by 5truja** [HewlettPackard/POSH-HPOneView#67]
Hi,
I am not able to connect to oneview appliance from powershell using FQDN. I get the following error:

Send-HPOVRequest : Acknowledgment of Login Message is required. Acknowledgment
of Login Message is required.
At C:\Users\adm127856\Documents\WindowsPowerShell\Modules\HPOneView.200\HPOneVi
ew.200.psm1:6045 char:21
+             $resp = Send-HPOVRequest $loginSessionsUri POST $_authinfo -Hostn
ame ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidOperation: (Send-HPOVRequest:String) [Sen
   d-HPOVRequest], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Send-HPOVRequest

**Comment by ChrisLynchHP** [comment]
The error isn't caused by you using an FQDN to attempt connecting to your appliance.  It is that your appliance has a Login Banner/Message configured.  I haven't added support for accepting the Login Message yet.  I will look into that today.

**Comment by 5truja** [comment]
Hi Chris,
Thank you for your reply. I did not have this kind of issue while using 1.2 OV. 
So basically there should be a way to work around this in 2.0 OV?
Thanking in advance

**Comment by ChrisLynchHP** [comment]
That's because 1.20 didn't have a Login Message feature.  Log into your HPE OneView Appliance, go to the top level menu, select Settings, then click on the Security panel Edit link when you hover into it.  You will see Login as a header, with a message and Acknowledgement.  If Acknowledgement is set to Required, then all access to the appliance, including via the API, needs to provide an accept request.  I haven't added support for that feature yet.

I'll likely add a new parameter, -LoginAcknowledge (or something like that), which will accept the login banner.  If it is not passed, and the API returns the error you reported, I will have the CMDLET display the login message and provide a prompt for interactive purposes.

**Comment by 5truja** [comment]
Hi Chris,
Thanks for a quick reply. I tried it and it works like a charm. 
Have a nice weekend

**Comment by ChrisLynchHP** [comment]
I'm sorry, but what worked?

**Comment by 5truja** [comment]
Sorry, I was not clear. Workaround.

Med v?nlig h?lsning,
Mladen Brekalo


19 feb. 2016 kl. 17:02 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


I'm sorry, but what worked?

-

**Comment by ChrisLynchHP** [comment]
I have added Login Message acknowledgement support to the v2.0.233.0 release.

**Comment by 5truja** [comment]
Hi Chris,

I'll check that on Monday.

Thanks a lot.
Have a nice weekend.

Med v?nlig h?lsning,
Mladen Brekalo


20 feb. 2016 kl. 06:42 skrev Chris Lynch <notifications@github.com<mailto:notifications@github.com>>:


I have added Login Message acknowledgement support to the v2.0.233.0 release.

-
